% This class defines a DDS Topic Type for use with the DDS Toolbox PSP.
% This class was automatically generated by the DDS Toolbox PSP utility
% DDS.import();
%
% Filename                :Color
% MATLAB version          :9.7
% DDS Toolbox PSP version :Unknown
% File generated on       :19-Jan-2022 12:38:10
%

classdef Color
properties
a = uint8(0);
r = uint8(0);
g = uint8(0);
b = uint8(0);
end

methods (Static = true)
% return a vector of booleans indicating which fields are
% keys.
function keyFields = getKeyFields()
    keyFields = logical([0 0 0 0 ]);
end
% return a vector of booleans indicating which fields are
% sequences.
function sequenceFields = getSequenceFields()
    sequenceFields = logical([0 0 0 0 ]);
end
% return a vector of booleans indicating which fields are
% optional.
function optionalFields = getOptionalFields()
    optionalFields = logical([0 0 0 0 ]);
end
end
end
