% This class defines a DDS Topic Type for use with the DDS Toolbox PSP.
% This class was automatically generated by the DDS Toolbox PSP utility
% DDS.import();
%
% Filename                :Pose2D
% MATLAB version          :9.7
% DDS Toolbox PSP version :Unknown
% File generated on       :19-Jan-2022 12:39:22
%

classdef Pose2D
properties
x = double(0);
y = double(0);
yaw = double(0);
end

methods (Static = true)
% return a vector of booleans indicating which fields are
% keys.
function keyFields = getKeyFields()
    keyFields = logical([0 0 0 ]);
end
% return a vector of booleans indicating which fields are
% sequences.
function sequenceFields = getSequenceFields()
    sequenceFields = logical([0 0 0 ]);
end
% return a vector of booleans indicating which fields are
% optional.
function optionalFields = getOptionalFields()
    optionalFields = logical([0 0 0 ]);
end
end
end
