% This class defines a DDS Topic Type for use with the DDS Toolbox PSP.
% This class was automatically generated by the DDS Toolbox PSP utility
% DDS.import();
%
% Filename                :HlcPlan
% MATLAB version          :9.7
% DDS Toolbox PSP version :Unknown
% File generated on       :26-Jan-2022 10:15:45
%

classdef HlcPlan
properties
vehicle_id = uint8(0);
output = repmat(double(0), 1, 100);
end

methods (Static = true)
% return a vector of booleans indicating which fields are
% keys.
function keyFields = getKeyFields()
    keyFields = logical([1 0 ]);
end
% return a vector of booleans indicating which fields are
% sequences.
function sequenceFields = getSequenceFields()
    sequenceFields = logical([0 1 ]);
end
% return a vector of booleans indicating which fields are
% optional.
function optionalFields = getOptionalFields()
    optionalFields = logical([0 0 ]);
end
end
end
